import { TestBed } from '@angular/core/testing';

import { AngularSdkComponentsComponent } from './angular-sdk-components.component';

// Legacy placeholder component generated by the Angular library scaffold; it is not standalone.
describe('AngularSdkComponentsComponent', () => {
  it('renders its placeholder text', () => {
    TestBed.configureTestingModule({ declarations: [AngularSdkComponentsComponent] });
    const fixture = TestBed.createComponent(AngularSdkComponentsComponent);
    fixture.detectChanges();
    expect(fixture.nativeElement.textContent).toContain('angular-sdk-components works!');
  });
});
